### ISSUE TITLE
Roadmap to MIToS v1.0

### ISSUE THREAD

**Issue by diegozea** [diegozea/MIToS.jl#25]
- **Scripts**
 - [x] Write documentation
 - [x] Use -p in scripts
 - [x] Move general parts to Utils module
 - [x] Use STDIN & STDOUT (pipes)
 - [x] Use real flags
- **MSA**
 - [x] Add `keepinserts` option to `read`/`parse`
 - [x] Test mean PID
- **PDB**
 - [x] `distance` and `contact` taking vectors
 
### Optional
- [x] cMI
- [x] Pfam Doc
 - [x] pMI

**Comment by diegozea** [comment]
- [ ] [KL like in MISTIC](http://mistic.leloir.org.ar/docs/results_help.html#ProximityMI)

**Comment by diegozea** [comment]
Completed :tada: :smile:
